app = "play-plan-backend"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443
